
interface _GlobalComponents {
      'LayaoutFooter': typeof import("../components/Layaout/footer.vue")['default']
    'LayaoutHeader': typeof import("../components/Layaout/header.vue")['default']
    'UIButton': typeof import("../components/UI/Button.vue")['default']
    'UILogo': typeof import("../components/UI/logo.vue")['default']
    'MainAboutCart': typeof import("../components/main/about/Cart.vue")['default']
    'MainAboutInfo': typeof import("../components/main/about/Info.vue")['default']
    'MainAboutPogruzka': typeof import("../components/main/about/Pogruzka.vue")['default']
    'MainAboutWork': typeof import("../components/main/about/Work.vue")['default']
    'MainAbout': typeof import("../components/main/about/index.vue")['default']
    'MainFormModal': typeof import("../components/main/form/Modal.vue")['default']
    'MainFormRequestForm': typeof import("../components/main/form/RequestForm.vue")['default']
    'MainForm': typeof import("../components/main/form/index.vue")['default']
    'MainIndexAdvantages': typeof import("../components/main/index/advantages.vue")['default']
    'MainIndex': typeof import("../components/main/index/index.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyLayaoutFooter': typeof import("../components/Layaout/footer.vue")['default']
    'LazyLayaoutHeader': typeof import("../components/Layaout/header.vue")['default']
    'LazyUIButton': typeof import("../components/UI/Button.vue")['default']
    'LazyUILogo': typeof import("../components/UI/logo.vue")['default']
    'LazyMainAboutCart': typeof import("../components/main/about/Cart.vue")['default']
    'LazyMainAboutInfo': typeof import("../components/main/about/Info.vue")['default']
    'LazyMainAboutPogruzka': typeof import("../components/main/about/Pogruzka.vue")['default']
    'LazyMainAboutWork': typeof import("../components/main/about/Work.vue")['default']
    'LazyMainAbout': typeof import("../components/main/about/index.vue")['default']
    'LazyMainFormModal': typeof import("../components/main/form/Modal.vue")['default']
    'LazyMainFormRequestForm': typeof import("../components/main/form/RequestForm.vue")['default']
    'LazyMainForm': typeof import("../components/main/form/index.vue")['default']
    'LazyMainIndexAdvantages': typeof import("../components/main/index/advantages.vue")['default']
    'LazyMainIndex': typeof import("../components/main/index/index.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const LayaoutFooter: typeof import("../components/Layaout/footer.vue")['default']
export const LayaoutHeader: typeof import("../components/Layaout/header.vue")['default']
export const UIButton: typeof import("../components/UI/Button.vue")['default']
export const UILogo: typeof import("../components/UI/logo.vue")['default']
export const MainAboutCart: typeof import("../components/main/about/Cart.vue")['default']
export const MainAboutInfo: typeof import("../components/main/about/Info.vue")['default']
export const MainAboutPogruzka: typeof import("../components/main/about/Pogruzka.vue")['default']
export const MainAboutWork: typeof import("../components/main/about/Work.vue")['default']
export const MainAbout: typeof import("../components/main/about/index.vue")['default']
export const MainFormModal: typeof import("../components/main/form/Modal.vue")['default']
export const MainFormRequestForm: typeof import("../components/main/form/RequestForm.vue")['default']
export const MainForm: typeof import("../components/main/form/index.vue")['default']
export const MainIndexAdvantages: typeof import("../components/main/index/advantages.vue")['default']
export const MainIndex: typeof import("../components/main/index/index.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyLayaoutFooter: typeof import("../components/Layaout/footer.vue")['default']
export const LazyLayaoutHeader: typeof import("../components/Layaout/header.vue")['default']
export const LazyUIButton: typeof import("../components/UI/Button.vue")['default']
export const LazyUILogo: typeof import("../components/UI/logo.vue")['default']
export const LazyMainAboutCart: typeof import("../components/main/about/Cart.vue")['default']
export const LazyMainAboutInfo: typeof import("../components/main/about/Info.vue")['default']
export const LazyMainAboutPogruzka: typeof import("../components/main/about/Pogruzka.vue")['default']
export const LazyMainAboutWork: typeof import("../components/main/about/Work.vue")['default']
export const LazyMainAbout: typeof import("../components/main/about/index.vue")['default']
export const LazyMainFormModal: typeof import("../components/main/form/Modal.vue")['default']
export const LazyMainFormRequestForm: typeof import("../components/main/form/RequestForm.vue")['default']
export const LazyMainForm: typeof import("../components/main/form/index.vue")['default']
export const LazyMainIndexAdvantages: typeof import("../components/main/index/advantages.vue")['default']
export const LazyMainIndex: typeof import("../components/main/index/index.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
